name: Generate docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yaml'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Build documentation
        run: ./gradlew :library:dokkaHtml

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: library/build/docs
